name: carbon_design_system
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  provider: ^6.1.2
  very_good_analysis: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: IBM Plex Mono
      fonts:
        - asset: fonts/IBMPlexMono-Regular.ttf
        - asset: fonts/IBMPlexMono-Italic.ttf
          style: italic
    - family: IBM Plex Sans
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
        - asset: fonts/IBMPlexSans-Italic.ttf
          style: italic
        - asset: fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: fonts/IBMPlexSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: fonts/IBMPlexSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
